name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Static
      run: make ociv
    - name: upload binary
      uses: actions/upload-artifact@v4
      with:
        name: ociv
        path: ociv
